export const quotes = [
  "Life is what happens when you're busy making other plans. - John Lennon",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The best way to predict the future is to invent it. - Alan Kay",
  "If opportunity doesn't knock, build a door. - Milton Berle",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Keep your face always toward the sunshine - and shadows will fall behind you. - Walt Whitman",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "What we think, we become. - Buddha",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
  "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "The best revenge is massive success. - Frank Sinatra",
  "It always seems impossible until it is done. - Nelson Mandela",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "A journey of a thousand miles begins with a single step. - Lao Tzu",
  "Do not take life too seriously. You will never get out of it alive. - Elbert Hubbard",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. - Marie Curie",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
  "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
  "The only way to do great work is to love what you do. - Steve Jobs",
];
